# Generated by Django 5.2.3 on 2025-06-27 11:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="creator",
        ),
    ]
